### ISSUE TITLE
Inconsistent case in station dictionary

### ISSUE THREAD

**Issue by RobFryer** [ices-taf/OHAT#21]
Minor irritant, but Danish stations in the station dictionary are a mix of Country = Denmark and Country = DENMARK (the only country where this is the case).  I have now trapped for this.  It causes problems because all the data are submitted by Country (not Country_ISO) and are in the form Denmark, so one gets lulled into a false sense of security.  Is it possible to correct the Country column in the Station Dictionary so that it is consistent?  I don't mind which, but consistency with the data extraction would be good.

A bigger issue is resolving (at some point) whether we should be using Country or Country_ISO.

**Comment by HansMJ** [comment]
Yes that is inconsistent. For some reason the name for Denmark changed in the [ICES country vocab](https://vocab.ices.dk/?ref=22) in January. I have made a [request](https://github.com/ices-eg/DIG/issues/54) for it to be changed back again.

The issue of moving to ISO country (USO 3166) is as you say a bigger issue. Because of all the legacy imports Marilynn is now working on the plan is to wait until that has been completed (likely during 2022). This will have to be well communicated with all implicated parties, so there will be some communication on that needed. We will also need to do loads of smaller changes in summary/download views, import procedure etc.

**Comment by HansMJ** [comment]
Denmark has been changed back to use mixed case (Denmark) instead of the upper case version. This will be included in Station Dictionary outputs
