### ISSUE TITLE
Bug in rmarkdown html report

### ISSUE THREAD

**Issue by RobFryer** [ices-taf/OHAT#28]
Can't following error when trying to compile:
https://dome.ices.dk/OHAT/Home/GettrResult?seriesID=Germany_UE67%20PYR&matrix=Sediment&year=2022
And similarly for other PAHs at the same station.  Other stations seem to work fine.

Error.
An error occurred while processing your request.
Request ID: |81f5ea06-42beb9d24deb8a67.

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by HansMJ** [comment]
That is weird, I will do some debugging to see what is going on

**Comment by HansMJ** [comment]
Here is the log file generated from running the report script [log_Germany_UE67_PYR__sediment__2022.txt](https://github.com/ices-taf/OHAT/files/7601745/log_Germany_UE67_PYR__sediment__2022.txt)

At the end it says

> "Quitting from lines 624-625 (assessment_platform.Rmd) 
Error in mgcv::gam(formula, data = data, family = switch(type, logistic = "betar",  : 
  Model has more coefficients than data
Calls: render ... eval -> eval -> plot.ratio -> lapply -> FUN -> <Anonymous>"

So is this something that will need to be fixed in the assessment/report script?

**Comment by RobFryer** [comment]
Thanks Hans, this is an issue at my end.  It looks like the model hasn't converged, but my routines for checking convergence haven't picked it up.  I will look into it and confirm.  If that proves to be the case, I won't bother sending any updated markdown, but make sure it is sorted for the next run of the assessment.
